"""Add Stripe fields to User model

Revision ID: 1b95739c0e09
Revises: 214b6f870e4b
Create Date: 2024-10-03 03:51:56.892254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b95739c0e09'
down_revision = '214b6f870e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
