"""changed preferences

Revision ID: 214b6f870e4b
Revises: 2ffe3f57ec4a
Create Date: 2024-10-03 01:34:45.889405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214b6f870e4b'
down_revision = '2ffe3f57ec4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language_tone')
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('language_tone', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
