"""Add assistant personality, language tone, about me, and language fields

Revision ID: 2ffe3f57ec4a
Revises: 15afd4b9046d
Create Date: 2024-10-03 00:34:20.543170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffe3f57ec4a'
down_revision = '15afd4b9046d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_personality', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('language_tone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=64), nullable=True))
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.TEXT(), nullable=True))
        batch_op.drop_column('language')
        batch_op.drop_column('about_me')
        batch_op.drop_column('language_tone')
        batch_op.drop_column('assistant_personality')

    # ### end Alembic commands ###
