"""Add name field to User model

Revision ID: a54811e3996e
Revises: 312b7c92ceeb
Create Date: 2024-09-29 04:59:23.527756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54811e3996e'
down_revision = '312b7c92ceeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=False, server_default='Default Name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')

    # ### end Alembic commands ###
